### ISSUE TITLE
Criar tela de Menu para upload de foto

### ISSUE THREAD

**Issue by gabrielziegler3** [SmartMeat-UnB/smartmeat#1]
A tela será utilizada para escolher a opção de upload para que o sistema receba a foto do prato que o usuário deseja saber a receita.

- [x] Tela de menu contendo duas opções: tirar foto e abrir galeria de fotos.
- [x] Botões funcionais e restringindo os arquivos para somente arquivos de imagem.
- [x] Aparecer opção de pedir a receita logo após o upload da imagem com sucesso

**Comment by joao4018** [comment]
issue finalizada, não se encontra no modelo do protótipo.
