### ISSUE TITLE
Tela para adição de nome do usuário 

### ISSUE THREAD

**Issue by davialvb** [SmartMeat-UnB/smartmeat#12]
É necessário uma tela para adição do nome do Usuário
Segue o modelo do protótipo:

![image](https://user-images.githubusercontent.com/34287081/64926995-41f3ce80-d7f4-11e9-8718-18071b6b4217.png)

- [ ] Campo para o nome
- [x] Botão de Pronto

**Comment by joao4018** [comment]
Como anda essa issue? Gostaria de finalizar ela pra rodar a intro do app corretamente.

**Comment by joao4018** [comment]
lembro de ter comentado que faltava apenas salvar no cel, se for isso perde merge que eu do o review e aceito, depois eu finalizado essa parte. @Caiocbeleza

**Comment by Caiocbeleza** [comment]
Só falta salvar o nome que o usuário colocar no campo, quando o botão for clicado.

**Comment by joao4018** [comment]
massa se quiser passar a issue pra mim eu finalizo, att a branch e pede o merge. @Caiocbeleza
