### ISSUE TITLE
Informações sobre a churrasqueira

### ISSUE THREAD

**Issue by davialvb** [SmartMeat-UnB/smartmeat#14]
É necessário um indicador onde mostre algumas informações importantes sobre o uso da churrasqueira para que o  Usuário possa tomar decisões e ser informado.
Segue o modelo do protótipo:
![image](https://user-images.githubusercontent.com/34287081/64927069-8338ae00-d7f5-11e9-83cd-cffd97d6ef79.png)

- [x] Indicador de espeto
- [x] Indicador de tempo

**Comment by joao4018** [comment]
Aqui falta ajeitar o numero e colocar um temporizado de x a 0
