### ISSUE TITLE
Criar tela de configurações

### ISSUE THREAD

**Issue by gabrielziegler3** [SmartMeat-UnB/smartmeat#37]
Tela deve conter possibilidade de alteração dos campos:

- [ ] Nome
- [ ] Tempo de alarme da notificação
- [ ] Conexão (Bluetooth ou WiFi)

**Comment by davialvb** [comment]
Necessário criar a tela no protótipo antes se possível!

**Comment by gabrielziegler3** [comment]
> Necessário criar a tela no protótipo antes se possível!

Cria uma issue pra ela e a faca
