### ISSUE TITLE
problema com tamanho do botao na pagina de informacoes

### ISSUE THREAD

**Issue by joao4018** [SmartMeat-UnB/smartmeat#39]
![photo4999047135034976426](https://user-images.githubusercontent.com/29952415/67165539-adcdd780-f35c-11e9-9ee3-2ecc195ed3a4.jpg)

**Comment by joao4018** [comment]
Acontece quando nao cabe tudo na tela do celular

**Comment by davialvb** [comment]
Foi arrumado na branch refactor_app, da uma olhada e vê se esta tudo certo. Logo ela ira para a master.
