### ISSUE TITLE
Criar tela inicial 

### ISSUE THREAD

**Issue by gabrielziegler3** [SmartMeat-UnB/smartmeat#5]
Tela inicial que contempla primeira interação com o usuário.
Nessa tela o usuário deve ser capaz de conectar com o dispositivo na churrasqueira e receber um sinal de OK se tudo der certo ou de erro se algo der errado.
- [x] Botões para conexão com a churrasqueira.

**Comment by joao4018** [comment]
a parte do sinais nao foram implementadas, mas acho importante fazer o PR dessa primeira issue pra ter a base do projeto.

**Comment by gabrielziegler3** [comment]
nao precisa esperar os sinais chegarem, vamos trabalhar com mock dos dados

**Comment by joao4018** [comment]
To fazendo a issue de conectividade, e o flutter nao consegue conectar em uma rede wifi pelo app, tem uma solucao sendo desenvolvida mas nao funciona direito, ele salva o ssid e a senha, ai se o usuário desligar e ligar o wifi ele conecta.
